// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import Foundation;
@import CoreGraphics;
@import ObjectiveC;
@import QuartzCore;
@import CoreMedia;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC12AstraeaSwift21AccountViewController")
@interface AccountViewController : UIViewController
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)updateViewConstraints;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface AccountViewController (SWIFT_EXTENSION(AstraeaSwift))
@end

@class UICollectionView;

SWIFT_CLASS("_TtC12AstraeaSwift21AnchorsViewController")
@interface AnchorsViewController : UIViewController
@property (nonatomic, strong) UICollectionView * _Null_unspecified collectionView;
- (void)viewDidLoad;
- (void)updateViewConstraints;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionViewCell;
@class UICollectionViewLayout;
@class UIScrollView;

@interface AnchorsViewController (SWIFT_EXTENSION(AstraeaSwift)) <UICollectionViewDataSource, UICollectionViewDelegate, UIScrollViewDelegate, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end

@protocol AppConfigDelegate;
@class NSError;
@class User;
@class Moment;

SWIFT_CLASS("_TtC12AstraeaSwift9AppConfig")
@interface AppConfig : NSObject
@property (nonatomic, weak) id <AppConfigDelegate> _Nullable delegate;
+ (void)startWith:(NSString * _Nullable)userId;
+ (void)setAppConfigDelegateWithDelegate:(id <AppConfigDelegate> _Nullable)delegate;
+ (void)logout;
/// A Boolean value indicating whether the share action is enable. default ‘false’
/// \param enable If true, you must implement the AppConfigDelegate
///
+ (void)setShareEnableWithEnable:(BOOL)enable;
/// A Boolean value indicating whether the sdk play video. default ‘false’
/// \param isPlay If false, you must implement the AppConfigDelegate
///
+ (void)setPlayVideoWithIsPlay:(BOOL)isPlay;
/// Sets the night mode
/// \param isNight true for night mode, otherwise day mode.
///
+ (void)setNightModeWithIsNight:(BOOL)isNight;
/// Binds the user with the specified information.
/// \param userId the user identifier of the application
///
/// \param mobile mobile number, must be 11 digits.
///
/// \param nickname the nickname of the user, digit, alphabets or chinese.
///
/// \param avatar the avatar url, may be null.
///
/// \param gender 1 for male, 2 for female
///
+ (void)bindUserWithUserId:(NSString * _Nonnull)userId mobile:(NSString * _Nonnull)mobile nickname:(NSString * _Nonnull)nickname avatar:(NSString * _Nonnull)avatar gender:(NSInteger)gender completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Fetches the active user list asynchronously.
+ (void)fetchUserCountWithCompletion:(void (^ _Nonnull)(NSInteger, NSError * _Nullable))completion;
/// Fetches the active user list asynchronously.
+ (void)fetchActiveUsersWithCompletion:(void (^ _Nonnull)(NSArray<User *> * _Nullable, NSError * _Nullable))completion;
/// Fetches the moments data
+ (void)fetchMomentsWithPageSize:(NSInteger)pageSize completion:(void (^ _Nonnull)(NSArray<Moment *> * _Nullable, NSError * _Nullable))completion;
/// Test
+ (void)updateUserInfoWith:(NSString * _Null_unspecified)jsonString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP12AstraeaSwift17AppConfigDelegate_")
@protocol AppConfigDelegate <NSObject>
@optional
/// Called when need to login, should bind user when finished login
/// \param controller current view controller
///
- (void)requestLoginFrom:(UIViewController * _Nullable)controller;
/// Called when the share is needed
/// \param shareLink the share url
///
/// \param title the share title
///
/// \param summary the share summary
///
/// \param imageUrl the share image url
///
/// \param controller current view controller
///
- (void)willBeginShareWith:(NSString * _Nonnull)shareLink title:(NSString * _Nonnull)title summary:(NSString * _Nonnull)summary imageUrl:(NSString * _Nonnull)imageUrl from:(UIViewController * _Nullable)controller;
/// Called when the video need to play
/// \param url the url of the video
///
/// \param controller current view controller
///
- (void)willPlayVideoWith:(NSString * _Nonnull)url from:(UIViewController * _Nullable)controller;
@end


SWIFT_CLASS("_TtC12AstraeaSwift5Audio")
@interface Audio : NSObject <NSCoding>
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


@interface CABasicAnimation (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface CAGradientLayer (SWIFT_EXTENSION(AstraeaSwift))
@end


SWIFT_CLASS("_TtC12AstraeaSwift10CallButton")
@interface CallButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSFileManager (SWIFT_EXTENSION(AstraeaSwift))
+ (NSString * _Nonnull)documentsDir SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)cachesDir SWIFT_WARN_UNUSED_RESULT;
@end

@class NSString;
@class UIColor;
@class NSTextContainer;

SWIFT_CLASS("_TtC12AstraeaSwift15GrowingTextView")
@interface GrowingTextView : UITextView
@property (nonatomic) NSInteger maxLength;
@property (nonatomic) BOOL trimWhiteSpaceWhenEndEditing;
@property (nonatomic) CGFloat maxHeight;
@property (nonatomic, strong) NSString * _Nullable placeHolder;
@property (nonatomic, strong) UIColor * _Nullable placeHolderColor;
@property (nonatomic) CGFloat placeHolderLeftMargin;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)drawRect:(CGRect)rect;
@end


SWIFT_PROTOCOL("_TtP12AstraeaSwift23GrowingTextViewDelegate_")
@protocol GrowingTextViewDelegate <UITextViewDelegate>
@optional
- (void)textViewDidChangeHeight:(CGFloat)height;
@end

@class UILabel;
@class UIFont;
@class NSAttributedString;

SWIFT_CLASS("_TtC12AstraeaSwift21KMPlaceholderTextView")
@interface KMPlaceholderTextView : UITextView
@property (nonatomic, readonly, strong) UILabel * _Nonnull placeholderLabel;
@property (nonatomic, copy) NSString * _Nonnull placeholder;
@property (nonatomic, strong) UIColor * _Nonnull placeholderColor;
@property (nonatomic, strong) UIFont * _Null_unspecified font;
@property (nonatomic, strong) UIFont * _Nullable placeholderFont;
@property (nonatomic) NSTextAlignment textAlignment;
@property (nonatomic, copy) NSString * _Null_unspecified text;
@property (nonatomic, strong) NSAttributedString * _Null_unspecified attributedText;
@property (nonatomic) UIEdgeInsets textContainerInset;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end

@class Photo;
@class Video;

SWIFT_CLASS("_TtC12AstraeaSwift6Moment")
@interface Moment : NSObject <NSCoding>
@property (nonatomic, copy) NSString * _Nullable momentId;
@property (nonatomic, copy) NSString * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSArray<Photo *> * _Nullable smallImages;
@property (nonatomic, copy) NSArray<Photo *> * _Nullable bigImages;
@property (nonatomic, strong) Audio * _Nullable audio;
@property (nonatomic, strong) Video * _Nullable video;
@property (nonatomic, strong) User * _Nullable user;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


@interface Moment (SWIFT_EXTENSION(AstraeaSwift))
@end

@class UITableView;

SWIFT_CLASS("_TtC12AstraeaSwift21MomentsViewController")
@interface MomentsViewController : UIViewController
@property (nonatomic, strong) UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (void)updateViewConstraints;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AstraeaSwift5Photo")
@interface Photo : NSObject <NSCoding>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (NSString * _Nullable)photoUrl SWIFT_WARN_UNUSED_RESULT;
@end

@class UIImage;

/// ▶️ Player, simple way to play and stream media
SWIFT_CLASS("_TtC12AstraeaSwift6Player")
@interface Player : UIViewController
/// Local or remote URL for the file asset to be played.
/// \param url URL of the asset.
///
@property (nonatomic, copy) NSURL * _Nullable url;
/// Mutes audio playback when true.
@property (nonatomic) BOOL muted;
/// Volume for the player, ranging from 0.0 to 1.0 on a linear scale.
@property (nonatomic) float volume;
/// Specifies how the video is displayed within a player layer’s bounds.
/// The default value is <code>AVLayerVideoGravityResizeAspect</code>. See <code>FillMode</code> enum.
@property (nonatomic, copy) NSString * _Nonnull fillMode;
/// Pauses playback automatically when backgrounded.
@property (nonatomic) BOOL playbackPausesWhenBackgrounded;
/// Resumes playback when entering foreground.
@property (nonatomic) BOOL playbackResumesWhenEnteringForeground;
/// Playback automatically loops continuously when true.
@property (nonatomic) BOOL playbackLoops;
/// Playback freezes on last frame frame at end when true.
@property (nonatomic) BOOL playbackFreezesAtEnd;
/// Playback buffering size in seconds.
@property (nonatomic) double bufferSize;
/// Playback is not automatically triggered from state changes when true.
@property (nonatomic) BOOL playbackEdgeTriggered;
/// Maximum duration of playback.
@property (nonatomic, readonly) NSTimeInterval maximumDuration;
/// Media playback’s current time.
@property (nonatomic, readonly) NSTimeInterval currentTime;
/// The natural dimensions of the media.
@property (nonatomic, readonly) CGSize naturalSize;
/// Player view’s initial background color.
@property (nonatomic, strong) UIColor * _Nullable layerBackgroundColor;
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
/// Begins playback of the media from the beginning.
- (void)playFromBeginning;
/// Begins playback of the media from the current time.
- (void)playFromCurrentTime;
/// Pauses playback of the media.
- (void)pause;
/// Stops playback of the media.
- (void)stop;
/// Updates playback to the specified time.
/// \param time The time to switch to move the playback.
///
- (void)seekTo:(CMTime)time;
/// Updates playback to the specified time.
/// \param time The time to switch to move the playback.
///
/// \param completionHandler call block handler after seeking
///
- (void)seekTo:(CMTime)time completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)seekToTimeTo:(CMTime)time toleranceBefore:(CMTime)toleranceBefore toleranceAfter:(CMTime)toleranceAfter completionHandler:(void (^ _Nonnull)(void))completionHandler;
/// Updates the playback time to the specified time bound.
/// \param time The time to switch to move the playback.
///
/// \param toleranceBefore The tolerance allowed before time.
///
/// \param toleranceAfter The tolerance allowed after time.
///
- (void)seekToTimeTo:(CMTime)time toleranceBefore:(CMTime)toleranceBefore toleranceAfter:(CMTime)toleranceAfter;
/// Captures a snapshot of the current Player view.
///
/// returns:
/// A UIImage of the player view.
- (UIImage * _Nonnull)takeSnapshot SWIFT_WARN_UNUSED_RESULT;
@end


@interface Player (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface Player (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface Player (SWIFT_EXTENSION(AstraeaSwift))
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
@end


@interface Player (SWIFT_EXTENSION(AstraeaSwift))
@end

@class UIView;
@class UITouch;
@class UIEvent;
@class UITextField;
@class SCLButton;

SWIFT_CLASS("_TtC12AstraeaSwift12SCLAlertView")
@interface SCLAlertView : UIViewController
@property (nonatomic, strong) UIColor * _Nullable iconTintColor;
@property (nonatomic, strong) UIView * _Nullable customSubview;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (UITextField * _Nonnull)addTextField:(NSString * _Nullable)title SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)addTextView SWIFT_WARN_UNUSED_RESULT;
- (SCLButton * _Nonnull)addButton:(NSString * _Nonnull)title backgroundColor:(UIColor * _Nullable)backgroundColor textColor:(UIColor * _Nullable)textColor showDurationStatus:(BOOL)showDurationStatus action:(void (^ _Nonnull)(void))action SWIFT_WARN_UNUSED_RESULT;
- (SCLButton * _Nonnull)addButton:(NSString * _Nonnull)title backgroundColor:(UIColor * _Nullable)backgroundColor textColor:(UIColor * _Nullable)textColor showDurationStatus:(BOOL)showDurationStatus target:(id _Nonnull)target selector:(SEL _Nonnull)selector SWIFT_WARN_UNUSED_RESULT;
- (void)updateDurationStatus;
- (void)hideView;
@end


SWIFT_CLASS("_TtC12AstraeaSwift9SCLButton")
@interface SCLButton : UIButton
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class UIGestureRecognizer;

SWIFT_CLASS("_TtC12AstraeaSwift20SwiftyStarRatingView")
@interface SwiftyStarRatingView : UIControl
@property (nonatomic) CGFloat maximumValue;
@property (nonatomic) CGFloat minimumValue;
@property (nonatomic) CGFloat value;
@property (nonatomic) CGFloat spacing;
@property (nonatomic) BOOL allowsHalfStars;
@property (nonatomic) BOOL accurateHalfStars;
@property (nonatomic) BOOL continuous;
@property (nonatomic, strong) UIImage * _Nullable emptyStarImage;
@property (nonatomic, strong) UIImage * _Nullable halfStarImage;
@property (nonatomic, strong) UIImage * _Nullable filledStarImage;
@property (nonatomic) BOOL shouldBecomeFirstResponder;
@property (nonatomic, copy) BOOL (^ _Null_unspecified shouldBeginGesRecBlock)(UIGestureRecognizer * _Nonnull);
@property (nonatomic, getter=isEnabled) BOOL enabled;
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@property (nonatomic, strong) UIColor * _Null_unspecified tintColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
@end


@interface SwiftyStarRatingView (SWIFT_EXTENSION(AstraeaSwift))
- (BOOL)accessibilityActivate SWIFT_WARN_UNUSED_RESULT;
- (void)accessibilityIncrement;
- (void)accessibilityDecrement;
@end


@interface SwiftyStarRatingView (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface SwiftyStarRatingView (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface SwiftyStarRatingView (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface SwiftyStarRatingView (SWIFT_EXTENSION(AstraeaSwift))
- (BOOL)beginTrackingWithTouch:(UITouch * _Nonnull)touch withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (BOOL)continueTrackingWithTouch:(UITouch * _Nonnull)touch withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (void)endTrackingWithTouch:(UITouch * _Nullable)touch withEvent:(UIEvent * _Nullable)event;
- (void)cancelTrackingWithEvent:(UIEvent * _Nullable)event;
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12AstraeaSwift15TTNavigationBar")
@interface TTNavigationBar : UINavigationBar
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIButton (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UICollectionReusableView (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UIColor (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UIColor (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UIDevice (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UIImage (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UIImageView (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UINavigationBar (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UINavigationBar (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UITableViewCell (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UITableViewHeaderFooterView (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UITextField (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UITextView (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UIView (SWIFT_EXTENSION(AstraeaSwift))
@property (nonatomic) BOOL didSetupConstraints;
@end


@interface UIViewController (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface UIViewController (SWIFT_EXTENSION(AstraeaSwift))
@end

@class UINavigationItem;

@interface UIViewController (SWIFT_EXTENSION(AstraeaSwift))
@property (nonatomic, strong) TTNavigationBar * _Nullable navigationBar;
@property (nonatomic, strong) UINavigationItem * _Nullable tt_navigationItem;
@property (nonatomic) BOOL didSetupConstraints;
- (void)addTTNavigationBar:(NSString * _Nonnull)title;
@end


SWIFT_CLASS("_TtC12AstraeaSwift4User")
@interface User : NSObject <NSCoding>
@property (nonatomic, copy) NSString * _Nullable uId;
@property (nonatomic, copy) NSString * _Nullable nickName;
@property (nonatomic, copy) NSString * _Nullable userNo;
@property (nonatomic, copy) NSString * _Nullable area;
@property (nonatomic, copy) NSString * _Nullable remark;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@property (nonatomic, readonly) NSInteger hashValue;
- (BOOL)isAuth SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)identityImage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)avatarUrl SWIFT_WARN_UNUSED_RESULT;
/// Is male
///
/// returns:
/// false means is female
- (BOOL)isMale SWIFT_WARN_UNUSED_RESULT;
@end


@interface User (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface User (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface User (SWIFT_EXTENSION(AstraeaSwift))
@end


@interface User (SWIFT_EXTENSION(AstraeaSwift))
- (BOOL)isOnline SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isCalling SWIFT_WARN_UNUSED_RESULT;
@end


@interface User (SWIFT_EXTENSION(AstraeaSwift))
@end


SWIFT_CLASS("_TtC12AstraeaSwift5Video")
@interface Video : NSObject <NSCoding>
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (NSString * _Nullable)coverUrl SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)videoUrl SWIFT_WARN_UNUSED_RESULT;
@end

#pragma clang diagnostic pop
